apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.metadata.labels | indent 4 }}
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: {{ .Values.metadata.name }}
