kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.metadata.name }}
  labels:
{{ toYaml .Values.metadata.labels | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.metadata.name }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Values.metadata.name }}
  apiGroup: ""